[package]
name = "tmail"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["cargo"] }
rand = "0.8.5"
redb = "2.1.3"
serde_json = "1.0.128"
ureq = { version = "2.10.1", features = ["json"] }
